### ISSUE TITLE
EMNLP2022 RocketChat Task List

### ISSUE THREAD

**Issue by hao-fang** [acl-org/emnlp-2022-rocketchat#1]
This list is used to track the main tasks for RocketChat.

# Preparation
- [x] Sign a contract with RocketChat
  - [x] Get the estimated number of users from Priscilla.
     * We will start with 3500 users, and can upgrade as needed.
  - [x] Confirm with General Chair about the workspace name. 
    * We will use `emnlp2022.rocket.chat`.
  - [x] Get a trial account for the workspace for initial setup.
    * The trial account will be upgraded to a paid plan a few days before the conference. (For EMNLP2022, this will be Dec 1, 2022).
    *  The associated admin account can be your own personal email. You can also register a specific email (e.g., `emnlp2022rocketchat@gmail.com`) for this.
- [ ] Configure OAuth2 for SSO
  * We need to coordinate with Underline.io to see if this is possible. Otherwise, we need to figure out how to send log in credentials to participants.
- [x] Inform volunteer chairs about volunteer needs.
  - [x] We will need 3-4 volunteers who can work a few weeks before the conference starts to help set up the RocketChat workspace.
  - [x] We may also need some on-call volunteers to handle urgent requests (e.g., remove disturbing participants, etc.) 

# Setup the workspace
- [x] Create the "EMNLP2022 Admin Bot" account with full admin permissions. This bot can be used to create channels and make announcements. You can use a specific email for this account, e.g., `emnlp2022rocketchat@google.com` and it may be shared with multiple people.
  - [x] Change the profile photo of the "EMNLP2022 Admin Bot" to the ACL logo.
- [ ] Create channels
  - [x] Create general channels.  See #2 for the list of channels and their settings. Most of these channels should be created with the "EMNLP2022 Admin Bot" account so this account has the ownership. 
  - [x] Create channels for each tutorials. This can be manually done by 1 volunteer. You probably need to reach out to tutorial chairs about this.
  - [ ] ~Create channels for sponsors. Will need to first talk with the person who are in charge of the sponsor booths, probably Priscilla. We can skip this one if the sponsors do not need a channel.~
  - [ ] ~Create channels for social events. You will need to talk with social organizers to see their needs.~
  - [x] Create channels for papers (main conference, demo, CL, TACL, SRW), We can asked one volunteer to use [this script](https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/chat/make_poster_rooms.py) to automatically create these channels. We can check if EMNLP2020 have upgraded the scripts.
  - [x] Create channels for workshops using the same script or manually.
  - [ ] Mark channels that should be listed first in the "Browse Channels" page. Basically, all non-paper channels are "promoted".  See the column "Featured" [in this list](https://github.com/acl-org/emnlp-2020-virtual-conference/issues/69).
- [ ] Configure permissions and roles. Details TBD.
- [x] Upload emoji. (Just need the ACL org icon. The default emojis should be enough.)
- [ ] Go through the "Administration Panel" to check the configurations. See details in #70. Both of the below sub-tasks are optional since they should be already covered by #70.
- [ ] Assign volunteers to handle the #organizer-registration-desk.
- [ ] Talk to Professional Conduct Committee to understand their need.
- [ ] Volunteer training materials. See more in #50.
- [ ] Understand that we will recommend people to set up their "Display Name" with pronouns & affiliation. See step 6 in this [login instruction doc](https://docs.google.com/document/d/1dGEUg5jNZwyK2w8RLhmgvz-DXq-Xu2_ezAveOYYZzY4/edit). I guess there is no action item for this, but it's useful to keep this in mind when people ask about it. **(Nov. 11)**
- [ ] Before the conference starts, remind the RocketChat support team to scale up for upcoming traffics. (Just need to create a ticket in their support platform.)
- [ ] Before the conference starts, clean up the channels & chat history.
  - [ ] Remove test channels.
  - [ ] Prune message histories for all public channels.
  - [ ] Post a welcome message in #announcement using the Admin Bot account, and react with an :acl-logo emoji.
<img width="1220" alt="Screen Shot 2020-11-10 at 10 58 52 PM" src="https://user-images.githubusercontent.com/9957482/98779193-59066000-23a8-11eb-9095-a5a5f6ae1846.png">
- [ ] Create a tutorial / instruction video or doc to demonstrate how to use RocketChat in Underline.io, including the login, etc.

# During the conference

TBD
